# Generated by Django 5.0.3 on 2024-03-11 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True, verbose_name='Имя')),
                ('payment_system', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard')], max_length=20, verbose_name='Платежная система')),
                ('currency', models.CharField(choices=[('rub', 'RUB'), ('usd', 'USD'), ('eur', 'EUR')], max_length=20, verbose_name='Валюта')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Баланс')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_on', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL, verbose_name='Собственник')),
            ],
            options={
                'verbose_name': 'Кошелек',
                'verbose_name_plural': 'Кошельки',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Сумма перевода')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Комиссия')),
                ('status', models.CharField(choices=[('paid', 'PAID'), ('failed', 'FAILED')], max_length=10, verbose_name='Статус операции')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время операции')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='wallet_app.wallet', verbose_name='Кошелек получателя')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='wallet_app.wallet', verbose_name='Кошелек отправителя')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
                'ordering': ['-timestamp'],
            },
        ),
    ]
